### ISSUE TITLE
Einlesen eines Ordners erzeugt Fehlermeldung (in_array erwartet 2 Parameter, GcHelpers.php)

### ISSUE THREAD

**Issue by michelbalzer** [markocupic/gallery_creator#26]
Als ich gestern mehrere Galerien angelegt hatte und dann die Bilder aus dem Dateiverzeichnis einlesen wollte (Auswahl Ordner, keine einzelnden Dateien, gleiches Verzeichnis wie „Zugewiesenes Upload Verzeichnis“) erhielt ich, unter anderem, folgende (aus dem Log stammende und daher wohl gekürzte) Fehlermeldung:

```
[16-Nov-2015 16:43:20 Europe/Berlin] 
PHP Warning: in_array() expects parameter 2 to be array, null given in /system/modules/gallery_creator/src/classes/GcHelpers.php on line 1025
#0 [internal function]: __error(2, 'in_array() expe...', '/kunden/300762_...', 1025, Array)
#1 /system/modules/gallery_creator/src/classes/GcHelpers.php(1025): in_array('20131007 Besuch...', NULL)
#2 /system/cache/dca/tl_gallery_creator_albums.php(1179): MCupic\GalleryCreator\GcHelpers::importFromFilesystem('11', 'bc0edd51-5b81-1...')
#3 /system/modules/core/drivers/DC_Table.php(207): tl_gallery_creator_albums->onloadCbImportFromFilesystem(Object(Contao\DC_Table))
#4 /system/modules/core/classes/Backend.php(408): Contao\DC_Table->__construct('tl_gallery_crea...', Array)
#5 /system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('gallery_creator')
#6 /contao/main.php(20): Contao\BackendMain->run()
#7 {main}
```
Aus der Paketverwaltung:

```
{
    "name": "local/website",
    "description": "A local website project",
    "type": "project",
    "license": "proprietary",
    "require": {
        "comolo/contao-supertheme": ">=2.2.1.0,<2.3-dev",
        "contao-community-alliance/composer-client": "~0.12",
        "contao-legacy/frontend_editor": ">=2.2.6.9003,<2.3-dev",
        "contao-legacy/newslanguage": ">=2.1.0.9030,<2.2-dev",
        "dma/dma_elementgenerator": "dev-master",
        "markocupic/gallery_creator": ">=4.9.0.0,<4.10-dev",
        "psi/boxes4ward": ">=2.0.5.0,<2.1-dev",
        "terminal42/contao-changelanguage": ">=2.2.9.0,<2.3-dev"
    },
    "prefer-stable": true,
    "minimum-stability": "dev",
    "config": {
        "preferred-install": "dist",
        "cache-dir": "cache",
        "component-dir": "../assets/components"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://legacy-packages-via.contao-community-alliance.org/"
        },
        {
            "type": "artifact",
            "url": "packages"
        },
        {
            "type": "composer",
            "url": "http://legacy-packages-via.contao-community-alliance.org/"
        }
    ],
    "extra": {
        "contao": {
            "migrated": "done"
        }
    }
}
```

**Comment by markocupic** [comment]
solved!

**Comment by michelbalzer** [comment]
Yep, danke! 👍
